repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.3.0
  hooks:
    - id: check-merge-conflict
    - id: end-of-file-fixer
    - id: detect-aws-credentials
      args:
        - --allow-missing-credentials
    - id: detect-private-key
    - id: check-case-conflict
    - id: check-yaml
    - id: sort-simple-yaml
- repo: https://github.com/hadolint/hadolint
  rev: v2.10.0
  hooks:
    - id: hadolint
      args: [
        '--ignore', 'DL3007', # Latest upstream image is the intention
        '--ignore', 'DL3008', # Latest debian packages are good for security
        '--ignore', 'DL3013'  # Latest python packages are good for security
      ]
